int *input_vector(int *);
void output_vector(int, int *);
int **create_matrix(int, int);
int **create_input_matrix(int *, int *);
void output_matrix(int, int, int **);
int is_sorted_arr(int, int *, int (*)(int, int));
int perechi_elem_consec_identice(int, int *);
int exista_x_in_v(int, int, int *);
void cate_pos_neg_nule(int, int *, int *, int *, int *);
int copiere_comune(int, int, int *, int *, int *);
int val_minim_vector(int, int *);
int pozitiile_minimului(int, int *, int *);
int maxim_impar(int, int *);
void elimina_primul_elem_tot(int *, int *);
void pare_impare(int, int *, int *, int *, int *, int *);
void perm_circ_stanga(int, int *);
void perm_circ_dreapta(int, int *);
int arrays_identical(int, int, int *, int *);
int matrix_identical(int, int, int, int, int **, int **);
void interchange_vectors(int, int *, int *);
int sort_ascending(int, int);
int sort_descending(int, int);
void sort_vector(int, int *, int (*)(int, int));
void swap_vars(int *, int *);
int sum_arr(int, int *);
